// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-west-2',
  aws_cognito_identity_pool_id:
    'us-west-2:027ee2f6-0480-4282-9495-5e04dedafa1a',
  aws_cognito_region: 'us-west-2',
  aws_user_pools_id: 'us-west-2_ghjpKiKHV',
  aws_user_pools_web_client_id: '1q049i98vqgtac31h7l4ptkea7',
  aws_user_files_s3_bucket: 'mbcpf83ce0fbc3b2439d90078e3b9c0b0d5e',
  aws_user_files_s3_bucket_region: 'us-west-2'
};

export default awsmobile;
